### ISSUE TITLE
Not work :c

### ISSUE THREAD

**Issue by dewster** [Aelto/Rift-Wanderer#1]
Hi, all time drop this error: 
bundle.home.js:116 Uncaught Error: Could not search for a game, the app is not ready yet.data.global.waitForGame @ bundle.home.js:116click @ VM93:2(anonymous function) @ vue.js:1413

**Comment by Aelto** [comment]
Hi, this message appears when the app is not done yet with the cache updates and you try to spectate a game.

Is there any message in the console before the error, such as: [Rift Wanderer now uses the same version as Riot's client](https://github.com/Aelto/Rift-Wanderer/blob/master/src/home/main.js#L161) ?

You can also try to download again the 3 cache files. To force the app to "update" change the value of `gameVersion` in your [config.json](https://github.com/Aelto/Rift-Wanderer/blob/master/app/app-data/config.json#L5) file to `"0"` (It must be a String, thus contained in "").

Tell me if it worked, thank you.
