### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by Suburbanno** [Aelto/Rift-Wanderer#3]
download site no work

**Comment by Aelto** [comment]
Hi, as noted in the main readme of this project, it is no longer maintained for... _reasons_. However a better alternative is available which has roughly the same features as this project.

_i'm copy-pasting the section of the readme:_
> You may want to check [Stava](https://github.com/Aelto/Stava), which is roughly the same concept but a bit more advanced with a few new concepts. **This repository was created as an experiment and is no longer maintained, sorry for the wasted clicks**.

I'm also closing the issue and updating the description of the project to mention this is no longer maintained while also linking to the alternative. Thanks for your interest in the project.
